version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: message-broker
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_VHOST: Client
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq
      - ./.docker/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - default

networks:
  default:
    name: rabbitmq-client
    driver: bridge
